### ISSUE TITLE
Running tyton freeze my system

### ISSUE THREAD

**Issue by s1ckb017** [nbulischeck/tyton#24]
I tried to launch tyton in my VirtualBox system: `Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux`

I installed dependencies and compiled all.

When I run `insmod tyton.ko ` my system freeze and became unusable.

**Comment by nbulischeck** [comment]
Can you provide a stack trace of the kernel oops?

**Comment by nbulischeck** [comment]
This might be fixed in the recent merges. Closing this for now. Please reopen if you continue to experience issues.
