### ISSUE TITLE
The kernel module could not be built with the linux>=5.7.6

### ISSUE THREAD

**Issue by yu17** [nbulischeck/tyton#32]
Dear development team,

In a recent kernel patch, "kallsyms_lookup_name" was unexported, and building tyton on kernel>=5.7.6 fails.

I built tyton-1.2 under Blackarch on kernel 5.7.7-arch1-1 and the following error occurred:

**Error Message from pacman:**

    ==> dkms install --no-depmod -m tyton -v 1.2 -k 5.7.7-arch1-1  
    Error! Bad return status for module build on kernel: 5.7.7-arch1-1 (x86_64)  
    Consult /var/lib/dkms/tyton/1.2/build/make.log for more information.  
    ==> Warning, `dkms install --no-depmod -m tyton -v 1.2 -k 5.7.7-arch1-1' returned 10

**make.log**

    DKMS make.log for tyton-1.2 for kernel 5.7.7-arch1-1 (x86_64)            [0/184]
    2020-07-05T23:06:53 EDT
    make -C /lib/modules/5.7.7-arch1-1/build M=/var/lib/dkms/tyton/1.2/build modules
    make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
    make[1]: Entering directory '/usr/lib/modules/5.7.7-arch1-1/build'
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/core.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/util.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/proc.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/module_list.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/syscall_hooks.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/network_hooks.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/netfilter_hooks.o
      CC [M]  /var/lib/dkms/tyton/1.2/build/src/interrupt_hooks.o
      LD [M]  /var/lib/dkms/tyton/1.2/build/tyton.o
      MODPOST 1 modules
    ERROR: modpost: "kallsyms_lookup_name" [/var/lib/dkms/tyton/1.2/build/tyton.ko] undefined!
    make[2]: *** [scripts/Makefile.modpost:99: __modpost] Error 1
    make[1]: *** [Makefile:1645: modules] Error 2
    make[1]: Leaving directory '/usr/lib/modules/5.7.7-arch1-1/build'
    make: *** [Makefile:19: module] Error 2

So I wonder if there's any workaround for this issue, or I do have to compile my own kernel to make tyton work?

Best regards,
Yu

**Comment by nbulischeck** [comment]
Yu,

This repo wasn't set up properly from the start and doesn't have proper versioning.

Your issue was fixed in this commit: https://github.com/nbulischeck/tyton/commit/ae7988b572c5c4c01830d2af10e79cdf6ed87f19

You can try cloning from master and rebuilding.

Thanks,

Nick

**Comment by yu17** [comment]
Sorry about bringing up the same issue again. I didn't notice that it has been fixed already. And also thank you for replying me on that!!
